// Australian States and Territories (as a simple array)
export const AU_STATE = [
    "ACT",
    "NSW",
    "NT",
    "QLD",
    "VIC",
    "SA",
    "TAS",
    "WA"
  ];
  
  // All LGAs by state (as an object where keys are states and values are arrays of LGAs)
  export const LGA_BY_STATE = {
    "ACT": [
      "Australian Capital Territory"
    ],
    "NSW": [
      "Albury City Council",
      "Armidale Regional Council",
      "Ballina Shire Council",
      "Balranald Shire Council",
      "Bathurst Regional Council",
      "Bayside Council",
      "Bega Valley Shire Council",
      "Bellingen Shire Council",
      "Berrigan Shire Council",
      "Blacktown City Council",
      "Bland Shire Council",
      "Blayney Shire Council",
      "Blue Mountains City Council",
      "Bogan Shire Council",
      "Bourke Shire Council",
      "Brewarrina Shire Council",
      "Broken Hill City Council",
      "Burwood Council",
      "Byron Shire Council",
      "Cabonne Council",
      "Camden Council",
      "Campbelltown City Council",
      "Canada Bay City Council",
      "Canterbury-Bankstown Council",
      "Carrathool Shire Council",
      "Central Coast Council",
      "Central Darling Shire Council",
      "Cessnock City Council",
      "Clarence Valley Council",
      "Cobar Shire Council",
      "Coffs Harbour City Council",
      "Coolamon Shire Council",
      "Coonamble Shire Council",
      "Cootamundra-Gundagai Regional Council",
      "Cowra Shire Council",
      "Cumberland City Council",
      "Dubbo Regional Council",
      "Dungog Shire Council",
      "Edward River Council",
      "Eurobodalla Shire Council",
      "Fairfield City Council",
      "Federation Council",
      "Forbes Shire Council",
      "Georges River Council",
      "Gilgandra Shire Council",
      "Glen Innes Severn Council",
      "Goulburn Mulwaree Council",
      "Greater Hume Shire Council",
      "Griffith City Council",
      "Gunnedah Shire Council",
      "Gwydir Shire Council",
      "Hawkesbury City Council",
      "Hay Shire Council",
      "Hilltops Council",
      "Hornsby Shire Council",
      "Hunter's Hill Council",
      "Inner West Council",
      "Inverell Shire Council",
      "Junee Shire Council",
      "Kempsey Shire Council",
      "Kiama Municipal Council",
      "Ku-ring-gai Council",
      "Kyogle Council",
      "Lachlan Shire Council",
      "Lake Macquarie City Council",
      "Lane Cove Municipal Council",
      "Leeton Shire Council",
      "Lismore City Council",
      "Lithgow City Council",
      "Liverpool City Council",
      "Liverpool Plains Shire Council",
      "Lockhart Shire Council",
      "Maitland City Council",
      "Mid-Coast Council",
      "Mid-Western Regional Council",
      "Moree Plains Shire Council",
      "Mosman Municipal Council",
      "Murray River Council",
      "Murrumbidgee Council",
      "Muswellbrook Shire Council",
      "Nambucca Valley Council",
      "Narrabri Shire Council",
      "Narrandera Shire Council",
      "Narromine Shire Council",
      "Newcastle City Council",
      "North Sydney Council",
      "Northern Beaches Council",
      "Oberon Council",
      "Orange City Council",
      "Parkes Shire Council",
      "Parramatta City Council",
      "Penrith City Council",
      "Port Macquarie-Hastings Council",
      "Port Stephens Council",
      "Queanbeyan-Palerang Regional Council",
      "Randwick City Council",
      "Richmond Valley Council",
      "Ryde City Council",
      "Shellharbour City Council",
      "Shoalhaven City Council",
      "Singleton Council",
      "Snowy Monaro Regional Council",
      "Snowy Valleys Council",
      "Strathfield Municipal Council",
      "Sutherland Shire Council",
      "Sydney City Council",
      "Tamworth Regional Council",
      "Temora Shire Council",
      "Tenterfield Shire Council",
      "The Hills Shire Council",
      "Tweed Shire Council",
      "Upper Hunter Shire Council",
      "Upper Lachlan Shire Council",
      "Uralla Shire Council",
      "Wagga Wagga City Council",
      "Walcha Council",
      "Walgett Shire Council",
      "Warren Shire Council",
      "Warrumbungle Shire Council",
      "Waverley Council",
      "Weddin Shire Council",
      "Wentworth Shire Council",
      "Willoughby City Council",
      "Wingecarribee Shire Council",
      "Wollondilly Shire Council",
      "Wollongong City Council",
      "Woollahra Municipal Council",
      "Yass Valley Council"
    ],
    "NT": [
      "Alice Springs Town Council",
      "Barkly Regional Council",
      "Belyuen Community Government Council",
      "Central Desert Regional Council",
      "Coomalie Community Government Council",
      "Darwin City Council",
      "East Arnhem Regional Council",
      "Katherine Town Council",
      "Litchfield Council",
      "MacDonnell Regional Council",
      "Palmerston City Council",
      "Roper Gulf Regional Council",
      "Tiwi Islands Regional Council",
      "Victoria Daly Regional Council",
      "Wagait Shire Council",
      "West Arnhem Regional Council",
      "West Daly Regional Council"
    ],
    "QLD": [
      "Aurukun Shire Council",
      "Balonne Shire Council",
      "Banana Shire Council",
      "Barcaldine Regional Council",
      "Barcoo Shire Council",
      "Blackall-Tambo Regional Council",
      "Boulia Shire Council",
      "Brisbane City Council",
      "Bulloo Shire Council",
      "Bundaberg Regional Council",
      "Burdekin Shire Council",
      "Burke Shire Council",
      "Cairns Regional Council",
      "Carpentaria Shire Council",
      "Cassowary Coast Regional Council",
      "Central Highlands Regional Council",
      "Charters Towers Regional Council",
      "Cherbourg Aboriginal Shire Council",
      "Cloncurry Shire Council",
      "Cook Shire Council",
      "Croydon Shire Council",
      "Diamantina Shire Council",
      "Doomadgee Aboriginal Shire Council",
      "Douglas Shire Council",
      "Etheridge Shire Council",
      "Flinders Shire Council",
      "Fraser Coast Regional Council",
      "Gladstone Regional Council",
      "Gold Coast City Council",
      "Goondiwindi Regional Council",
      "Gympie Regional Council",
      "Hinchinbrook Shire Council",
      "Hope Vale Aboriginal Shire Council",
      "Ipswich City Council",
      "Isaac Regional Council",
      "Kowanyama Aboriginal Shire Council",
      "Livingstone Shire Council",
      "Lockhart River Aboriginal Shire Council",
      "Lockyer Valley Regional Council",
      "Logan City Council",
      "Longreach Regional Council",
      "Mackay Regional Council",
      "Mapoon Aboriginal Shire Council",
      "Maranoa Regional Council",
      "Mareeba Shire Council",
      "McKinlay Shire Council",
      "Moreton Bay Regional Council",
      "Mornington Shire Council",
      "Mount Isa City Council",
      "Murweh Shire Council",
      "Napranum Aboriginal Shire Council",
      "Noosa Shire Council",
      "North Burnett Regional Council",
      "Northern Peninsula Area Regional Council",
      "Palm Island Aboriginal Shire Council",
      "Paroo Shire Council",
      "Pormpuraaw Aboriginal Shire Council",
      "Quilpie Shire Council",
      "Redland City Council",
      "Richmond Shire Council",
      "Rockhampton Regional Council",
      "Scenic Rim Regional Council",
      "Somerset Regional Council",
      "South Burnett Regional Council",
      "Southern Downs Regional Council",
      "Sunshine Coast Regional Council",
      "Tablelands Regional Council",
      "Toowoomba Regional Council",
      "Torres Shire Council",
      "Torres Strait Island Regional Council",
      "Townsville City Council",
      "Weipa Town Authority",
      "Western Downs Regional Council",
      "Whitsunday Regional Council",
      "Winton Shire Council",
      "Woorabinda Aboriginal Shire Council",
      "Wujal Wujal Aboriginal Shire Council",
      "Yarrabah Aboriginal Shire Council"
    ],
    "SA": [
      "Adelaide City Council",
      "Adelaide Hills Council",
      "Adelaide Plains Council",
      "Alexandrina Council",
      "Barossa Council",
      "Barunga West Council",
      "Berri Barmera Council",
      "Burnside City Council",
      "Campbelltown City Council",
      "City of Charles Sturt",
      "Clare and Gilbert Valleys Council",
      "Cleve District Council",
      "Coober Pedy Council",
      "Copper Coast Council",
      "Elliston District Council",
      "Flinders Ranges Council",
      "Franklin Harbour District Council",
      "Gawler Town Council",
      "Goyder Regional Council",
      "Grant District Council",
      "Holdfast Bay City Council",
      "Kangaroo Island Council",
      "Karoonda East Murray District Council",
      "Kimba District Council",
      "Kingston District Council",
      "Light Regional Council",
      "Lower Eyre Peninsula District Council",
      "Loxton Waikerie District Council",
      "Marion City Council",
      "Mid Murray Council",
      "Mitcham City Council",
      "Mount Barker District Council",
      "Mount Gambier City Council",
      "Mount Remarkable District Council",
      "Murray Bridge City Council",
      "Naracoorte Lucindale Council",
      "Northern Areas Council",
      "Norwood Payneham and St Peters City Council",
      "Onkaparinga City Council",
      "Orroroo Carrieton District Council",
      "Peterborough District Council",
      "Playford City Council",
      "Port Adelaide Enfield City Council",
      "Port Augusta City Council",
      "Port Lincoln City Council",
      "Port Pirie Regional Council",
      "Prospect City Council",
      "Renmark Paringa District Council",
      "Robe District Council",
      "Roxby Downs Council",
      "Salisbury City Council",
      "Southern Mallee District Council",
      "Streaky Bay District Council",
      "Tatiara District Council",
      "Tea Tree Gully City Council",
      "Tumby Bay District Council",
      "Unley City Council",
      "Victor Harbor City Council",
      "Wakefield Regional Council",
      "Walkerville Town Council",
      "Wattle Range Council",
      "West Torrens City Council",
      "Whyalla City Council",
      "Wudinna District Council",
      "Yankalilla District Council",
      "Yorke Peninsula Council"
    ],
    "TAS": [
      "Break O'Day Council",
      "Brighton Council",
      "Burnie City Council",
      "Central Coast Council",
      "Central Highlands Council",
      "Circular Head Council",
      "Clarence City Council",
      "Derwent Valley Council",
      "Devonport City Council",
      "Dorset Council",
      "Flinders Council",
      "George Town Council",
      "Glamorgan Spring Bay Council",
      "Glenorchy City Council",
      "Hobart City Council",
      "Huon Valley Council",
      "Kentish Council",
      "Kingborough Council",
      "King Island Council",
      "Latrobe Council",
      "Launceston City Council",
      "Meander Valley Council",
      "Northern Midlands Council",
      "Sorell Council",
      "Southern Midlands Council",
      "Tasman Council",
      "Waratah-Wynyard Council",
      "West Coast Council",
      "West Tamar Council"
    ],
    "VIC": [
      "Alpine Shire Council",
      "Ararat Rural City Council",
      "Ballarat City Council",
      "Banyule City Council",
      "Bass Coast Shire Council",
      "Baw Baw Shire Council",
      "Bayside City Council",
      "Benalla Rural City Council",
      "Boroondara City Council",
      "Brimbank City Council",
      "Buloke Shire Council",
      "Campaspe Shire Council",
      "Cardinia Shire Council",
      "Casey City Council",
      "Central Goldfields Shire Council",
      "Colac Otway Shire Council",
      "Corangamite Shire Council",
      "Darebin City Council",
      "East Gippsland Shire Council",
      "Frankston City Council",
      "Gannawarra Shire Council",
      "Glen Eira City Council",
      "Glenelg Shire Council",
      "Golden Plains Shire Council",
      "Greater Bendigo City Council",
      "Greater Dandenong City Council",
      "Greater Geelong City Council",
      "Greater Shepparton City Council",
      "Hepburn Shire Council",
      "Hindmarsh Shire Council",
      "Hobsons Bay City Council",
      "Horsham Rural City Council",
      "Hume City Council",
      "Indigo Shire Council",
      "Kingston City Council",
      "Knox City Council",
      "Latrobe City Council",
      "Loddon Shire Council",
      "Macedon Ranges Shire Council",
      "Manningham City Council",
      "Mansfield Shire Council",
      "Maribyrnong City Council",
      "Maroondah City Council",
      "Melbourne City Council",
      "Melton City Council",
      "Mildura Rural City Council",
      "Mitchell Shire Council",
      "Moira Shire Council",
      "Monash City Council",
      "Moonee Valley City Council",
      "Moorabool Shire Council",
      "Moreland City Council",
      "Mornington Peninsula Shire Council",
      "Mount Alexander Shire Council",
      "Moyne Shire Council",
      "Murrindindi Shire Council",
      "Nillumbik Shire Council",
      "Northern Grampians Shire Council",
      "Port Phillip City Council",
      "Pyrenees Shire Council",
      "Queenscliffe Borough Council",
      "South Gippsland Shire Council",
      "Southern Grampians Shire Council",
      "Stonnington City Council",
      "Strathbogie Shire Council",
      "Surf Coast Shire Council",
      "Swan Hill Rural City Council",
      "Towong Shire Council",
      "Wangaratta Rural City Council",
      "Warrnambool City Council",
      "Wellington Shire Council",
      "West Wimmera Shire Council",
      "Whitehorse City Council",
      "Whittlesea City Council",
      "Wodonga City Council",
      "Wyndham City Council",
      "Yarra City Council",
      "Yarra Ranges Shire Council",
      "Yarriambiack Shire Council"
    ],
    "WA": [
      "Albany City Council",
      "Armadale City Council",
      "Ashburton Shire Council",
      "Augusta-Margaret River Shire Council",
      "Bassendean Town Council",
      "Bayswater City Council",
      "Belmont City Council",
      "Beverley Shire Council",
      "Boddington Shire Council",
      "Boyup Brook Shire Council",
      "Bridgetown-Greenbushes Shire Council",
      "Brookton Shire Council",
      "Broome Shire Council",
      "Broomehill-Tambellup Shire Council",
      "Bruce Rock Shire Council",
      "Bunbury City Council",
      "Busselton City Council",
      "Cambridge Town Council",
      "Canning City Council",
      "Capel Shire Council",
      "Carnamah Shire Council",
      "Carnarvon Shire Council",
      "Chapman Valley Shire Council",
      "Chittering Shire Council",
      "Christmas Island Shire Council",
      "Claremont Town Council",
      "Cockburn City Council",
      "Cocos (Keeling) Islands Shire Council",
      "Collie Shire Council",
      "Coolgardie Shire Council",
      "Coorow Shire Council",
      "Corrigin Shire Council",
      "Cottesloe Town Council",
      "Cranbrook Shire Council",
      "Cuballing Shire Council",
      "Cue Shire Council",
      "Cunderdin Shire Council",
      "Dalwallinu Shire Council",
      "Dandaragan Shire Council",
      "Dardanup Shire Council",
      "Denmark Shire Council",
      "Derby-West Kimberley Shire Council",
      "Donnybrook-Balingup Shire Council",
      "Dowerin Shire Council",
      "Dumbleyung Shire Council",
      "Dundas Shire Council",
      "East Fremantle Town Council",
      "East Pilbara Shire Council",
      "Esperance Shire Council",
      "Exmouth Shire Council",
      "Fremantle City Council",
      "Gingin Shire Council",
      "Gnowangerup Shire Council",
      "Goomalling Shire Council",
      "Gosnells City Council",
      "Greater Geraldton City Council",
      "Halls Creek Shire Council",
      "Harvey Shire Council",
      "Irwin Shire Council",
      "Jerramungup Shire Council",
      "Joondalup City Council",
      "Kalamunda City Council",
      "Kalgoorlie-Boulder City Council",
      "Karratha City Council",
      "Katanning Shire Council",
      "Kellerberrin Shire Council",
      "Kent Shire Council",
      "Kojonup Shire Council",
      "Kondinin Shire Council",
      "Koorda Shire Council",
      "Kulin Shire Council",
      "Kwinana City Council",
      "Lake Grace Shire Council",
      "Laverton Shire Council",
      "Leonora Shire Council",
      "Mandurah City Council",
      "Manjimup Shire Council",
      "Meekatharra Shire Council",
      "Melville City Council",
      "Menzies Shire Council",
      "Merredin Shire Council",
      "Mingenew Shire Council",
      "Moora Shire Council",
      "Morawa Shire Council",
      "Mosman Park Town Council",
      "Mount Magnet Shire Council",
      "Mount Marshall Shire Council",
      "Mukinbudin Shire Council",
      "Mundaring Shire Council",
      "Murchison Shire Council",
      "Murray Shire Council",
      "Nannup Shire Council",
      "Narembeen Shire Council",
      "Narrogin Shire Council",
      "Nedlands City Council",
      "Ngaanyatjarraku Shire Council",
      "Northam Shire Council",
      "Northampton Shire Council",
      "Nungarin Shire Council",
      "Peppermint Grove Shire Council",
      "Perenjori Shire Council",
      "Perth City Council",
      "Pingelly Shire Council",
      "Plantagenet Shire Council",
      "Port Hedland Town Council",
      "Quairading Shire Council",
      "Ravensthorpe Shire Council",
      "Rockingham City Council",
      "Sandstone Shire Council",
      "Serpentine-Jarrahdale Shire Council",
      "Shark Bay Shire Council",
      "South Perth City Council",
      "Stirling City Council",
      "Subiaco City Council",
      "Swan City Council",
      "Tammin Shire Council",
      "Three Springs Shire Council",
      "Toodyay Shire Council",
      "Trayning Shire Council",
      "Upper Gascoyne Shire Council",
      "Victoria Park Town Council",
      "Victoria Plains Shire Council",
      "Vincent City Council",
      "Wagin Shire Council",
      "Wandering Shire Council",
      "Wanneroo City Council",
      "Waroona Shire Council",
      "West Arthur Shire Council",
      "Westonia Shire Council",
      "Wickepin Shire Council",
      "Williams Shire Council",
      "Wiluna Shire Council",
      "Wongan-Ballidu Shire Council",
      "Woodanilling Shire Council",
      "Wyalkatchem Shire Council",
      "Wyndham-East Kimberley Shire Council",
      "Yalgoo Shire Council",
      "Yilgarn Shire Council",
      "York Shire Council"
    ]
  };
  